export const WILL_FETCH_RICKY_AND_MORTY_DATA = 'WILL_FETCH_RICKY_AND_MORTY_DATA'
export const FETCHING_RICKY_AND_MORTY_DATA = 'FETCHING_RICKY_AND_MORTY_DATA'
export const DID_FETCH_RICKY_AND_MORTY_DATA = 'DID_FETCH_RICKY_AND_MORTY_DATA'
