const chokidar = require('chokidar');

const { createFile } = require('./utils/configFileCreator');
const {
  PUBLIC_VIEWS_FOLDER_PATH,
  PUBLIC_VIEWS_CONFIG_FILE_PATH,
  PUBLIC_VIEWS_ADDITIONAL_CONFIG_FILE_PATH,
  PRIVATE_VIEWS_FOLDER_PATH,
  PRIVATE_VIEWS_CONFIG_FILE_PATH,
  PRIVATE_VIEWS_ADDITIONAL_CONFIG_FILE_PATH,
} = require('./config/constants');

let watcher = chokidar.watch(PUBLIC_VIEWS_FOLDER_PATH, {});

watcher
.on('add', createFile(PUBLIC_VIEWS_FOLDER_PATH, PUBLIC_VIEWS_CONFIG_FILE_PATH, PUBLIC_VIEWS_ADDITIONAL_CONFIG_FILE_PATH))
.on('change', createFile(PUBLIC_VIEWS_FOLDER_PATH, PUBLIC_VIEWS_CONFIG_FILE_PATH, PUBLIC_VIEWS_ADDITIONAL_CONFIG_FILE_PATH))
.on('unlink', createFile(PUBLIC_VIEWS_FOLDER_PATH, PUBLIC_VIEWS_CONFIG_FILE_PATH, PUBLIC_VIEWS_ADDITIONAL_CONFIG_FILE_PATH));

watcher = chokidar.watch(PRIVATE_VIEWS_FOLDER_PATH, {});

watcher
.on('add', createFile(PRIVATE_VIEWS_FOLDER_PATH, PRIVATE_VIEWS_CONFIG_FILE_PATH, PRIVATE_VIEWS_ADDITIONAL_CONFIG_FILE_PATH))
.on('change', createFile(PRIVATE_VIEWS_FOLDER_PATH, PRIVATE_VIEWS_CONFIG_FILE_PATH, PRIVATE_VIEWS_ADDITIONAL_CONFIG_FILE_PATH))
.on('unlink', createFile(PRIVATE_VIEWS_FOLDER_PATH, PRIVATE_VIEWS_CONFIG_FILE_PATH, PRIVATE_VIEWS_ADDITIONAL_CONFIG_FILE_PATH));

